#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-promises
Version  : 1.0.1
Release  : 11
URL      : https://cran.r-project.org/src/contrib/promises_1.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/promises_1.0.1.tar.gz
Summary  : Abstractions for Promise-Based Asynchronous Programming
Group    : Development/Tools
License  : MIT
Requires: R-promises-lib = %{version}-%{release}
BuildRequires : R-Rcpp
BuildRequires : R-cli
BuildRequires : R-future
BuildRequires : R-globals
BuildRequires : R-later
BuildRequires : R-listenv
BuildRequires : R-purrr
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
# promises
[![Build Status](https://travis-ci.org/rstudio/promises.svg?branch=master)](https://travis-ci.org/rstudio/promises)

%package lib
Summary: lib components for the R-promises package.
Group: Libraries

%description lib
lib components for the R-promises package.


%prep
%setup -q -c -n promises

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552873638

%install
export SOURCE_DATE_EPOCH=1552873638
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library promises
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library promises
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library promises
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc  promises || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/promises/DESCRIPTION
/usr/lib64/R/library/promises/INDEX
/usr/lib64/R/library/promises/LICENSE
/usr/lib64/R/library/promises/Meta/Rd.rds
/usr/lib64/R/library/promises/Meta/features.rds
/usr/lib64/R/library/promises/Meta/hsearch.rds
/usr/lib64/R/library/promises/Meta/links.rds
/usr/lib64/R/library/promises/Meta/nsInfo.rds
/usr/lib64/R/library/promises/Meta/package.rds
/usr/lib64/R/library/promises/Meta/vignette.rds
/usr/lib64/R/library/promises/NAMESPACE
/usr/lib64/R/library/promises/NEWS.md
/usr/lib64/R/library/promises/R/promises
/usr/lib64/R/library/promises/R/promises.rdb
/usr/lib64/R/library/promises/R/promises.rdx
/usr/lib64/R/library/promises/doc/combining.Rmd
/usr/lib64/R/library/promises/doc/combining.html
/usr/lib64/R/library/promises/doc/futures.Rmd
/usr/lib64/R/library/promises/doc/futures.html
/usr/lib64/R/library/promises/doc/index.html
/usr/lib64/R/library/promises/doc/intro.Rmd
/usr/lib64/R/library/promises/doc/intro.html
/usr/lib64/R/library/promises/doc/motivation.Rmd
/usr/lib64/R/library/promises/doc/motivation.html
/usr/lib64/R/library/promises/doc/overview.Rmd
/usr/lib64/R/library/promises/doc/overview.html
/usr/lib64/R/library/promises/doc/shiny.Rmd
/usr/lib64/R/library/promises/doc/shiny.html
/usr/lib64/R/library/promises/help/AnIndex
/usr/lib64/R/library/promises/help/aliases.rds
/usr/lib64/R/library/promises/help/paths.rds
/usr/lib64/R/library/promises/help/promises.rdb
/usr/lib64/R/library/promises/help/promises.rdx
/usr/lib64/R/library/promises/html/00Index.html
/usr/lib64/R/library/promises/html/R.css
/usr/lib64/R/library/promises/tests/testthat.R
/usr/lib64/R/library/promises/tests/testthat/common.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-1.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-2.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-3.R
/usr/lib64/R/library/promises/tests/testthat/test-combining.R
/usr/lib64/R/library/promises/tests/testthat/test-methods.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/promises/libs/promises.so
