#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
#
Name     : R-promises
Version  : 1.2.1
Release  : 44
URL      : https://cran.r-project.org/src/contrib/promises_1.2.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/promises_1.2.1.tar.gz
Summary  : Abstractions for Promise-Based Asynchronous Programming
Group    : Development/Tools
License  : MIT
Requires: R-promises-lib = %{version}-%{release}
Requires: R-R6
Requires: R-Rcpp
Requires: R-fastmap
Requires: R-later
Requires: R-magrittr
Requires: R-rlang
BuildRequires : R-R6
BuildRequires : R-Rcpp
BuildRequires : R-fastmap
BuildRequires : R-future
BuildRequires : R-later
BuildRequires : R-magrittr
BuildRequires : R-rlang
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
programming in R using promises. Asynchronous programming is useful
    for allowing a single R process to orchestrate multiple tasks in the
    background while also attending to something else. Semantics are
    similar to 'JavaScript' promises, but with a syntax that is idiomatic
    R.

%package lib
Summary: lib components for the R-promises package.
Group: Libraries

%description lib
lib components for the R-promises package.


%prep
%setup -q -n promises
pushd ..
cp -a promises buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1691717757

%install
export SOURCE_DATE_EPOCH=1691717757
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/promises/DESCRIPTION
/usr/lib64/R/library/promises/INDEX
/usr/lib64/R/library/promises/LICENSE
/usr/lib64/R/library/promises/Meta/Rd.rds
/usr/lib64/R/library/promises/Meta/features.rds
/usr/lib64/R/library/promises/Meta/hsearch.rds
/usr/lib64/R/library/promises/Meta/links.rds
/usr/lib64/R/library/promises/Meta/nsInfo.rds
/usr/lib64/R/library/promises/Meta/package.rds
/usr/lib64/R/library/promises/Meta/vignette.rds
/usr/lib64/R/library/promises/NAMESPACE
/usr/lib64/R/library/promises/NEWS.md
/usr/lib64/R/library/promises/R/promises
/usr/lib64/R/library/promises/R/promises.rdb
/usr/lib64/R/library/promises/R/promises.rdx
/usr/lib64/R/library/promises/WORDLIST
/usr/lib64/R/library/promises/doc/index.html
/usr/lib64/R/library/promises/doc/promises_01_motivation.Rmd
/usr/lib64/R/library/promises/doc/promises_01_motivation.html
/usr/lib64/R/library/promises/doc/promises_02_intro.Rmd
/usr/lib64/R/library/promises/doc/promises_02_intro.html
/usr/lib64/R/library/promises/doc/promises_03_overview.Rmd
/usr/lib64/R/library/promises/doc/promises_03_overview.html
/usr/lib64/R/library/promises/doc/promises_04_futures.Rmd
/usr/lib64/R/library/promises/doc/promises_04_futures.html
/usr/lib64/R/library/promises/doc/promises_05_future_promise.R
/usr/lib64/R/library/promises/doc/promises_05_future_promise.Rmd
/usr/lib64/R/library/promises/doc/promises_05_future_promise.html
/usr/lib64/R/library/promises/doc/promises_06_shiny.Rmd
/usr/lib64/R/library/promises/doc/promises_06_shiny.html
/usr/lib64/R/library/promises/doc/promises_07_combining.Rmd
/usr/lib64/R/library/promises/doc/promises_07_combining.html
/usr/lib64/R/library/promises/doc/promises_08_casestudy.Rmd
/usr/lib64/R/library/promises/doc/promises_08_casestudy.html
/usr/lib64/R/library/promises/help/AnIndex
/usr/lib64/R/library/promises/help/aliases.rds
/usr/lib64/R/library/promises/help/figures/lifecycle-archived.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-defunct.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-deprecated.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-experimental.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-maturing.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-questioning.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-stable.svg
/usr/lib64/R/library/promises/help/figures/lifecycle-superseded.svg
/usr/lib64/R/library/promises/help/paths.rds
/usr/lib64/R/library/promises/help/promises.rdb
/usr/lib64/R/library/promises/help/promises.rdx
/usr/lib64/R/library/promises/html/00Index.html
/usr/lib64/R/library/promises/html/R.css
/usr/lib64/R/library/promises/tests/spelling.R
/usr/lib64/R/library/promises/tests/testthat.R
/usr/lib64/R/library/promises/tests/testthat/common.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-1.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-2.R
/usr/lib64/R/library/promises/tests/testthat/test-aplus-2-3.R
/usr/lib64/R/library/promises/tests/testthat/test-combining.R
/usr/lib64/R/library/promises/tests/testthat/test-domains.R
/usr/lib64/R/library/promises/tests/testthat/test-methods.R
/usr/lib64/R/library/promises/tests/testthat/test-visibility.R
/usr/lib64/R/library/promises/tests/testthat/test-zzz-future_promise.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/promises/libs/promises.so
/usr/lib64/R/library/promises/libs/promises.so.avx2
/usr/lib64/R/library/promises/libs/promises.so.avx512
